### ISSUE TITLE
Integrating Power-Genome for Unit-level data

### ISSUE THREAD

**Issue by ktehranchi** [ktehranchi/pypsa-breakthroughenergy-usa#8]

**Comment by ktehranchi** [comment]
- up to date
- - Greg Shivley

**Comment by ktehranchi** [comment]
@Gabriel

- How up to date is power-genome data? What is the source of each data point?
- Download + develop some test cases
- understand settings in power-genome
- GPS locations for power plants
- How are renewable profiles generated? (are they generated in the tool?)

**Comment by gabrielreyg** [comment]
test
